name: 📸 EHS Daily Report Automation

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 7 AM PKT (UTC+5)
  workflow_dispatch:      # Allows manual run from GitHub

jobs:
  ehs-daily-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install Dependencies
        run: npm ci

      - name: 🎭 Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: 🧪 Run Screenshot Test
        run: npx playwright test
        env:
          LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

      - name: 📤 Send Screenshot to Discord
        run: npx ts-node scripts/send-to-discord.ts
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: 📧 Send Screenshot by Email
        run: npx ts-node scripts/send-email.ts
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
