name: 📸 EHS Daily Report Automation

on:
  schedule:
    - cron: '0 13 * * *'  # Runs at 7 AM Pakistan Time (UTC+5)
  workflow_dispatch:

permissions:
  contents: write  # 👈 Required to push changes to the repo

jobs:
  ehs-daily-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install Dependencies
        run: npm ci

      - name: 🎭 Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: 🧪 Run Screenshot Test
        run: npx playwright test
        env:
          LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

      - name: 📝 Commit & Push Screenshot to Repo
        run: |
          git config --global user.name "EHS Bot"
          git config --global user.email "ehs-bot@ehs.edu.pk"

          git add screenshots/*.png
          git commit -m "📸 Add screenshot for $(date +'%Y-%m-%d %H:%M:%S')" || echo "⚠️ Nothing to commit"
          git push
          
